import { useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { IconAction, PrimaryButton } from "@/components/app-ui";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol, type SKIconName } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";
import type { FinancialEntryType } from "@/shared/business";

const types: { id: FinancialEntryType; label: string; description: string; icon: SKIconName }[] = [
  { id: "cost", label: "Custo", description: "Ligado à mercadoria ou entrega.", icon: "shippingbox.fill" }, { id: "expense", label: "Despesa", description: "Mantém o negócio funcionando.", icon: "arrow.down.right" }, { id: "withdrawal", label: "Retirada", description: "Dinheiro tirado pelo empreendedor.", icon: "arrow.up.right" }, { id: "capital", label: "Capital", description: "Dinheiro colocado no negócio.", icon: "arrow.down.right" }, { id: "reserve", label: "Reserva", description: "Proteção para estabilidade.", icon: "lock.fill" },
];
const today = () => new Date().toISOString().slice(0, 10);
const toCents = (value: string) => Math.round((Number(value.replace(/[^0-9,]/g, "").replace(",", ".")) || 0) * 100);

export default function NewFinancialEntryScreen() {
  const colors = useColors(); const router = useRouter(); const utils = trpc.useUtils(); const [type, setType] = useState<FinancialEntryType>("expense"); const [amount, setAmount] = useState(""); const [description, setDescription] = useState(""); const [date, setDate] = useState(today());
  const create = trpc.finances.createEntry.useMutation({ onSuccess: async () => { await utils.workspace.get.invalidate(); Alert.alert("Lançamento salvo", "Seu caixa e seus indicadores foram atualizados.", [{ text: "Continuar", onPress: () => router.replace("/financas" as never) }]); }, onError: (error) => Alert.alert("Não foi possível salvar", error.message) });
  const save = () => { const parsedDate = new Date(`${date}T12:00:00`); if (toCents(amount) <= 0 || description.trim().length < 2 || Number.isNaN(parsedDate.getTime())) { Alert.alert("Revise o lançamento", "Informe um valor positivo, uma descrição e uma data no formato AAAA-MM-DD."); return; } create.mutate({ type, amountCents: toCents(amount), description: description.trim(), occurredAt: parsedDate }); };
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-4"><KeyboardAvoidingView style={styles.page} behavior={Platform.OS === "ios" ? "padding" : undefined}><View style={styles.top}><IconAction icon="chevron.left" label="Voltar" onPress={() => router.back()} /><View><Text style={[styles.eyebrow, { color: colors.primary }]}>FINANÇAS</Text><Text style={[styles.title, { color: colors.foreground }]}>Novo lançamento</Text></View></View><Text style={[styles.intro, { color: colors.muted }]}>Classifique o movimento para entender de onde vem e para onde vai o dinheiro do negócio.</Text><View style={styles.types}>{types.map((item) => <Pressable key={item.id} onPress={() => setType(item.id)} style={({ pressed }) => [styles.type, { borderColor: type === item.id ? colors.primary : colors.border, backgroundColor: type === item.id ? `${colors.primary}0D` : colors.surface }, pressed && styles.pressed]}><IconSymbol name={item.icon} size={19} color={type === item.id ? colors.primary : colors.muted} /><View style={styles.typeText}><Text style={[styles.typeLabel, { color: type === item.id ? colors.primary : colors.foreground }]}>{item.label}</Text><Text style={[styles.typeDescription, { color: colors.muted }]}>{item.description}</Text></View></Pressable>)}</View><View style={styles.form}><LabelInput label="Valor" value={amount} onChangeText={setAmount} placeholder="0,00" prefix="R$" keyboardType="decimal-pad" colors={colors} /><LabelInput label="Descrição" value={description} onChangeText={setDescription} placeholder="Ex.: Combustível para entrega" colors={colors} /><LabelInput label="Data" value={date} onChangeText={setDate} placeholder="AAAA-MM-DD" colors={colors} /></View><View style={styles.bottom}><PrimaryButton label="Salvar lançamento" icon="checkmark.circle.fill" onPress={save} loading={create.isPending} /></View></KeyboardAvoidingView></ScreenContainer>;
}
function LabelInput({ label, prefix, colors, ...props }: { label: string; prefix?: string; colors: ReturnType<typeof useColors>; value: string; onChangeText: (value: string) => void; placeholder: string; keyboardType?: "default" | "decimal-pad" }) { return <View style={styles.field}><Text style={[styles.label, { color: colors.foreground }]}>{label}</Text><View style={[styles.inputWrap, { backgroundColor: colors.surface, borderColor: colors.border }]}>{prefix ? <Text style={[styles.prefix, { color: colors.muted }]}>{prefix}</Text> : null}<TextInput {...props} style={[styles.input, { color: colors.foreground }]} placeholderTextColor={colors.muted} returnKeyType="done" /></View></View>; }
const styles = StyleSheet.create({ page: { flex: 1, paddingTop: 11, paddingBottom: 6 }, top: { flexDirection: "row", alignItems: "center", gap: 12 }, eyebrow: { fontSize: 10, fontWeight: "800", letterSpacing: 1 }, title: { fontSize: 25, lineHeight: 31, fontWeight: "800" }, intro: { fontSize: 13, lineHeight: 19, marginTop: 17, marginBottom: 14 }, types: { gap: 8 }, type: { minHeight: 61, borderWidth: 1, borderRadius: 16, paddingHorizontal: 13, flexDirection: "row", alignItems: "center", gap: 10 }, typeText: { flex: 1, gap: 2 }, typeLabel: { fontSize: 14, fontWeight: "800" }, typeDescription: { fontSize: 11, lineHeight: 15, fontWeight: "600" }, form: { gap: 13, marginTop: 19 }, field: { gap: 7 }, label: { fontSize: 12, fontWeight: "800" }, inputWrap: { height: 51, borderWidth: 1, borderRadius: 14, flexDirection: "row", alignItems: "center", paddingHorizontal: 13 }, prefix: { marginRight: 6, fontSize: 14, fontWeight: "800" }, input: { flex: 1, height: "100%", fontSize: 15, fontWeight: "600" }, bottom: { flex: 1, justifyContent: "flex-end", paddingTop: 15 }, pressed: { opacity: 0.7, transform: [{ scale: 0.98 }] } });
