import { useMemo, useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { Card, EmptyState, IconAction, LoadingState, PrimaryButton } from "@/components/app-ui";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useWorkspace } from "@/hooks/use-workspace";
import { useSaleCart } from "@/lib/sale-cart";
import { trpc } from "@/lib/trpc";
import { formatBRL, type PaymentMethod } from "@/shared/business";

const payments: { id: PaymentMethod; label: string; icon: "banknote.fill" | "checkmark.circle.fill" | "creditcard.fill" | "arrow.clockwise" }[] = [
  { id: "cash", label: "Dinheiro", icon: "banknote.fill" }, { id: "pix", label: "Pix", icon: "checkmark.circle.fill" }, { id: "card", label: "Cartão", icon: "creditcard.fill" }, { id: "credit", label: "Fiado", icon: "arrow.clockwise" },
];

export default function SaleReviewScreen() {
  const colors = useColors(); const router = useRouter(); const utils = trpc.useUtils(); const { lines, clear } = useSaleCart(); const { data, isLoading } = useWorkspace(); const [payment, setPayment] = useState<PaymentMethod>("pix");
  const rows = useMemo(() => lines.flatMap((line) => { const product = data?.workspace?.products.find((item) => item.id === line.productId); const mode = product?.exitModes.find((item) => item.id === line.exitModeId); return product && mode ? [{ ...line, product, mode, subtotalCents: mode.priceCents * line.quantity }] : []; }), [data?.workspace?.products, lines]);
  const total = rows.reduce((sum, row) => sum + row.subtotalCents, 0); const units = rows.reduce((sum, row) => sum + row.quantity * row.mode.stockUnits, 0);
  const sale = trpc.sales.create.useMutation({ onSuccess: async () => { clear(); await utils.workspace.get.invalidate(); Alert.alert("Venda registrada", "O estoque e os indicadores foram atualizados.", [{ text: "Continuar", onPress: () => router.replace("/(tabs)/index" as never) }]); }, onError: (error) => Alert.alert("Não foi possível concluir", error.message) });
  if (isLoading) return <ScreenContainer><LoadingState /></ScreenContainer>;
  if (!rows.length) return <ScreenContainer className="p-4"><View style={styles.top}><IconAction icon="chevron.left" label="Voltar" onPress={() => router.back()} /></View><EmptyState icon="cart.fill" title="Sua venda está vazia" description="Escolha uma modalidade de saída antes de revisar a venda." actionLabel="Voltar para vender" onAction={() => router.replace("/(tabs)/vender")} /></ScreenContainer>;
  return <ScreenContainer className="px-4"><FlatList data={rows} keyExtractor={(row) => String(row.exitModeId)} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><View style={styles.heading}><IconAction icon="chevron.left" label="Voltar" onPress={() => router.back()} /><View><Text style={[styles.eyebrow, { color: colors.primary }]}>FECHAR VENDA</Text><Text style={[styles.title, { color: colors.foreground }]}>Confira a saída</Text></View></View><Card style={[styles.totalCard, { backgroundColor: colors.foreground, borderColor: colors.foreground }]}><Text style={styles.totalLabel}>TOTAL DA VENDA</Text><Text style={styles.totalValue}>{formatBRL(total)}</Text><Text style={styles.totalSub}>{units} galão{units !== 1 ? "ões" : ""} serão baixados do estoque.</Text></Card><Text style={[styles.section, { color: colors.foreground }]}>Itens</Text></View>} renderItem={({ item }) => <View style={[styles.item, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.itemIcon, { backgroundColor: `${colors.primary}16` }]}><IconSymbol name="drop.fill" size={19} color={colors.primary} /></View><View style={styles.itemInfo}><Text style={[styles.itemName, { color: colors.foreground }]}>{item.product.name}</Text><Text style={[styles.itemMeta, { color: colors.muted }]}>{item.mode.name} · {item.quantity} saída{item.quantity > 1 ? "s" : ""}</Text></View><Text style={[styles.itemAmount, { color: colors.foreground }]}>{formatBRL(item.subtotalCents)}</Text></View>} ListFooterComponent={<View style={styles.footer}><Text style={[styles.section, { color: colors.foreground }]}>Meio de pagamento</Text><View style={styles.paymentGrid}>{payments.map((item) => <Pressable key={item.id} onPress={() => setPayment(item.id)} style={({ pressed }) => [styles.payment, { borderColor: payment === item.id ? colors.primary : colors.border, backgroundColor: payment === item.id ? `${colors.primary}12` : colors.surface }, pressed && styles.pressed]}><IconSymbol name={item.icon as never} size={19} color={payment === item.id ? colors.primary : colors.muted} /><Text style={[styles.paymentLabel, { color: payment === item.id ? colors.primary : colors.foreground }]}>{item.label}</Text></Pressable>)}</View><PrimaryButton label="Confirmar venda" icon="checkmark.circle.fill" onPress={() => sale.mutate({ paymentMethod: payment, items: rows.map((row) => ({ exitModeId: row.exitModeId, quantity: row.quantity })) })} loading={sale.isPending} /></View>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 15, paddingBottom: 36, gap: 10 }, top: { paddingVertical: 16 }, header: { gap: 16, marginBottom: 4 }, heading: { flexDirection: "row", alignItems: "center", gap: 12 }, eyebrow: { fontSize: 10, fontWeight: "800", letterSpacing: 1 }, title: { fontSize: 27, lineHeight: 33, fontWeight: "800", letterSpacing: -0.5 }, totalCard: { gap: 5, padding: 19 }, totalLabel: { fontSize: 11, fontWeight: "800", color: "#BCE7FA", letterSpacing: 0.8 }, totalValue: { fontSize: 32, lineHeight: 39, fontWeight: "800", color: "#FFFFFF", letterSpacing: -0.8 }, totalSub: { fontSize: 12, lineHeight: 18, fontWeight: "600", color: "#CFE0EA" }, section: { fontSize: 17, fontWeight: "800", marginTop: 4 }, item: { minHeight: 73, borderWidth: 1, borderRadius: 17, padding: 12, flexDirection: "row", alignItems: "center", gap: 10 }, itemIcon: { width: 39, height: 39, borderRadius: 12, alignItems: "center", justifyContent: "center" }, itemInfo: { flex: 1, gap: 3 }, itemName: { fontSize: 14, fontWeight: "800" }, itemMeta: { fontSize: 11, lineHeight: 16, fontWeight: "600" }, itemAmount: { fontSize: 14, fontWeight: "800" }, footer: { gap: 12, marginTop: 9 }, paymentGrid: { flexDirection: "row", flexWrap: "wrap", gap: 9, marginBottom: 7 }, payment: { width: "48.5%", minHeight: 60, borderWidth: 1, borderRadius: 15, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 8 }, paymentLabel: { fontSize: 13, fontWeight: "800" }, pressed: { opacity: 0.7, transform: [{ scale: 0.98 }] } });
