import { useMemo } from "react";
import { FlatList, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { Card, EmptyState, IconAction, LoadingState } from "@/components/app-ui";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol, type SKIconName } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useWorkspace } from "@/hooks/use-workspace";
import { calculateMetrics, formatBRL } from "@/shared/business";

export default function IndicatorsScreen() {
  const colors = useColors(); const router = useRouter(); const { data, isLoading } = useWorkspace(); const workspace = data?.workspace; const metrics = useMemo(() => workspace ? calculateMetrics(workspace.products, workspace.sales, workspace.saleItems, workspace.financialEntries) : null, [workspace]);
  if (isLoading || !workspace || !metrics) return <ScreenContainer><LoadingState /></ScreenContainer>;
  if (!workspace.sales.length && !workspace.financialEntries.length) return <ScreenContainer className="p-4"><View style={styles.top}><IconAction icon="chevron.left" label="Voltar" onPress={() => router.back()} /></View><EmptyState icon="chart.bar.fill" title="Seus indicadores vão aparecer aqui" description="Depois da primeira venda ou lançamento, você verá explicações e sugestões para decidir melhor." actionLabel="Começar uma venda" onAction={() => router.replace("/(tabs)/vender" as never)} /></ScreenContainer>;
  const indicators: { title: string; value: string; definition: string; suggestion: string; icon: SKIconName; attention?: boolean }[] = [
    { title: "Faturamento", value: formatBRL(metrics.revenueCents), definition: "É a soma de todas as vendas registradas no período.", suggestion: metrics.revenueCents ? "Compare com sua meta mensal para planejar as próximas vendas." : "Registre vendas para acompanhar a receita.", icon: "cart.fill" },
    { title: "Resultado líquido", value: formatBRL(metrics.netResultCents), definition: "É a receita depois dos custos e despesas operacionais.", suggestion: metrics.netResultCents < 0 ? "Revise preço, custos e despesas antes de retirar dinheiro." : "Proteja uma parte desse resultado para a reposição.", icon: "chart.bar.fill", attention: metrics.netResultCents < 0 },
    { title: "Margem líquida", value: metrics.netMargin === null ? "Ainda não calculada" : `${Math.round(metrics.netMargin * 100)}%`, definition: "Mostra quanto sobra de cada real vendido após os gastos operacionais.", suggestion: metrics.netMargin !== null && metrics.netMargin < 0.1 ? "Avalie o preço e os custos da operação." : "Acompanhe a margem ao alterar preços ou custos.", icon: "info.circle.fill", attention: metrics.netMargin !== null && metrics.netMargin < 0.1 },
    { title: "Caixa", value: formatBRL(metrics.cashCents), definition: "É o dinheiro disponível depois das entradas e saídas registradas.", suggestion: metrics.cashCents < 0 ? "Registre capital ou reduza saídas para recuperar o caixa." : "Separe o dinheiro da reposição antes de fazer retiradas.", icon: "banknote.fill", attention: metrics.cashCents < 0 },
    { title: "Capital de giro", value: formatBRL(metrics.workingCapitalCents), definition: "É o recurso disponível para compras, estoque e compromissos da operação.", suggestion: "Mantenha esse valor protegido para a próxima reposição.", icon: "arrow.clockwise" },
    { title: "Reserva", value: formatBRL(metrics.reserveCents), definition: "É o valor separado para proteger o negócio de imprevistos.", suggestion: "Crie lançamentos de reserva sempre que puder, mesmo que sejam pequenos.", icon: "lock.fill" },
    { title: "Ticket médio", value: metrics.ticketAverageCents === null ? "Ainda não calculado" : formatBRL(metrics.ticketAverageCents), definition: "É o faturamento dividido pela quantidade de vendas.", suggestion: "Use-o para acompanhar se cada venda está gerando mais receita.", icon: "banknote.fill" },
    { title: "Valor em estoque", value: formatBRL(metrics.inventoryValueCents), definition: "É o saldo de galões multiplicado pelo custo por unidade.", suggestion: metrics.lowStockCount ? "Há itens no mínimo: planeje a reposição antes de perder venda." : "Estoque é dinheiro aplicado. Evite deixar produto parado.", icon: "shippingbox.fill", attention: metrics.lowStockCount > 0 },
  ];
  return <ScreenContainer className="px-4"><FlatList data={indicators} keyExtractor={(item) => item.title} contentContainerStyle={styles.list} ListHeaderComponent={<View style={styles.header}><View style={styles.heading}><IconAction icon="chevron.left" label="Voltar" onPress={() => router.back()} /><View><Text style={[styles.eyebrow, { color: colors.primary }]}>LEITURA SIMPLES</Text><Text style={[styles.title, { color: colors.foreground }]}>Indicadores</Text></View></View><Text style={[styles.intro, { color: colors.muted }]}>Entenda o que cada número revela sobre a sua distribuidora.</Text></View>} renderItem={({ item }) => <Card style={[styles.item, item.attention ? { borderColor: colors.warning } : undefined]}><View style={styles.itemTop}><View style={[styles.iconWrap, { backgroundColor: `${item.attention ? colors.warning : colors.primary}16` }]}><IconSymbol name={item.icon} size={19} color={item.attention ? colors.warning : colors.primary} /></View><Text style={[styles.value, { color: colors.foreground }]}>{item.value}</Text></View><Text style={[styles.itemTitle, { color: colors.foreground }]}>{item.title}</Text><Text style={[styles.definition, { color: colors.muted }]}>{item.definition}</Text><View style={[styles.suggestion, { backgroundColor: `${colors.primary}0C` }]}><Text style={[styles.suggestionText, { color: colors.foreground }]}>{item.suggestion}</Text></View></Card>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ top: { paddingVertical: 4 }, list: { paddingTop: 14, paddingBottom: 34, gap: 11 }, header: { gap: 11, marginBottom: 2 }, heading: { flexDirection: "row", alignItems: "center", gap: 12 }, eyebrow: { fontSize: 10, fontWeight: "800", letterSpacing: 1 }, title: { fontSize: 27, lineHeight: 33, fontWeight: "800" }, intro: { fontSize: 13, lineHeight: 19 }, item: { gap: 8 }, itemTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, iconWrap: { width: 38, height: 38, borderRadius: 12, alignItems: "center", justifyContent: "center" }, value: { fontSize: 20, fontWeight: "800", letterSpacing: -0.3 }, itemTitle: { fontSize: 16, fontWeight: "800", marginTop: 2 }, definition: { fontSize: 13, lineHeight: 19 }, suggestion: { marginTop: 3, borderRadius: 12, padding: 11 }, suggestionText: { fontSize: 12, lineHeight: 17, fontWeight: "700" } });
