import { useEffect, useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { BrandMark } from "@/components/brand-mark";
import { IconAction, PrimaryButton } from "@/components/app-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { useWorkspace } from "@/hooks/use-workspace";
import { useAuth } from "@/hooks/use-auth";
import { trpc } from "@/lib/trpc";
import { useQueryClient } from "@tanstack/react-query";

const toCents = (value: string) => Math.round((Number(value.replace(/[^0-9,]/g, "").replace(",", ".")) || 0) * 100);
const fromCents = (value: number) => (value / 100).toFixed(2).replace(".", ",");

export default function ProfileScreen() {
  const colors = useColors(); const router = useRouter(); const queryClient = useQueryClient(); const { data } = useWorkspace(); const { user, logout } = useAuth(); const utils = trpc.useUtils(); const business = data?.business; const [name, setName] = useState(""); const [monthlyGoal, setMonthlyGoal] = useState(""); const [reserveGoal, setReserveGoal] = useState("");
  useEffect(() => { if (business) { setName(business.name); setMonthlyGoal(fromCents(business.monthlyGoalCents)); setReserveGoal(fromCents(business.reserveGoalCents)); } }, [business]);
  const update = trpc.workspace.update.useMutation({ onSuccess: async () => { await utils.workspace.get.invalidate(); Alert.alert("Perfil atualizado", "As metas do seu negócio foram salvas."); }, onError: (error) => Alert.alert("Não foi possível atualizar", error.message) });
  if (!business) return null;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-4"><KeyboardAvoidingView style={styles.page} behavior={Platform.OS === "ios" ? "padding" : undefined}><View style={styles.header}><IconAction icon="chevron.left" label="Voltar" onPress={() => router.back()} /><Text style={[styles.title, { color: colors.foreground }]}>Perfil do negócio</Text></View><View style={[styles.brandCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><BrandMark size={54} /><View style={{ flex: 1 }}><Text style={[styles.businessName, { color: colors.foreground }]}>{business.name}</Text><Text style={[styles.userEmail, { color: colors.muted }]}>{user?.email ?? "Conta sincronizada"}</Text></View></View><View style={styles.form}><Field label="Nome do negócio" value={name} onChangeText={setName} placeholder="Nome do negócio" colors={colors} /><Field label="Meta mensal de vendas" value={monthlyGoal} onChangeText={setMonthlyGoal} placeholder="0,00" prefix="R$" keyboardType="decimal-pad" colors={colors} /><Field label="Meta de reserva" value={reserveGoal} onChangeText={setReserveGoal} placeholder="0,00" prefix="R$" keyboardType="decimal-pad" colors={colors} /></View><View style={styles.bottom}><PrimaryButton label="Salvar perfil" icon="checkmark.circle.fill" onPress={() => { if (name.trim().length < 2) { Alert.alert("Informe o nome do negócio"); return; } update.mutate({ name: name.trim(), monthlyGoalCents: toCents(monthlyGoal), reserveGoalCents: toCents(reserveGoal) }); }} loading={update.isPending} /><Pressable onPress={async () => { await logout(); queryClient.clear(); router.replace("/login"); }} style={({ pressed }) => [styles.logout, { borderColor: colors.error }, pressed && styles.pressed]}><Text style={[styles.logoutText, { color: colors.error }]}>Sair da conta</Text></Pressable></View></KeyboardAvoidingView></ScreenContainer>;
}
function Field({ label, prefix, colors, ...props }: { label: string; prefix?: string; colors: ReturnType<typeof useColors>; value: string; onChangeText: (value: string) => void; placeholder: string; keyboardType?: "default" | "decimal-pad" }) { return <View style={styles.field}><Text style={[styles.label, { color: colors.foreground }]}>{label}</Text><View style={[styles.inputWrap, { borderColor: colors.border, backgroundColor: colors.surface }]}>{prefix ? <Text style={[styles.prefix, { color: colors.muted }]}>{prefix}</Text> : null}<TextInput {...props} style={[styles.input, { color: colors.foreground }]} placeholderTextColor={colors.muted} returnKeyType="done" /></View></View>; }
const styles = StyleSheet.create({ page: { flex: 1, paddingTop: 11, paddingBottom: 8 }, header: { flexDirection: "row", alignItems: "center", gap: 12 }, title: { fontSize: 24, fontWeight: "800" }, brandCard: { marginTop: 22, borderWidth: 1, borderRadius: 20, minHeight: 84, padding: 14, flexDirection: "row", alignItems: "center", gap: 12 }, businessName: { fontSize: 16, fontWeight: "800" }, userEmail: { fontSize: 12, marginTop: 3, fontWeight: "600" }, form: { marginTop: 25, gap: 14 }, field: { gap: 7 }, label: { fontSize: 12, fontWeight: "800" }, inputWrap: { height: 51, borderWidth: 1, borderRadius: 14, flexDirection: "row", alignItems: "center", paddingHorizontal: 13 }, prefix: { fontSize: 14, fontWeight: "800", marginRight: 6 }, input: { height: "100%", flex: 1, fontSize: 15, fontWeight: "600" }, bottom: { flex: 1, justifyContent: "flex-end", gap: 10 }, logout: { minHeight: 49, alignItems: "center", justifyContent: "center", borderRadius: 15, borderWidth: 1 }, logoutText: { fontSize: 14, fontWeight: "800" }, pressed: { opacity: 0.7, transform: [{ scale: 0.98 }] } });
