import { formatBRL } from "../shared/business";

const escapeHtml = (value: string) => value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[character] ?? character);

type ReportProduct = { productName: string; unitsSold: number; currentStockUnits: number; inventoryValueCents: number; revenueCents: number; isLowStock: boolean; hasNoSales: boolean };
type ReportMetrics = { netResultCents: number; revenueCents: number; salesCount: number; soldStockUnits: number; ticketAverageCents: number | null; inventoryValueCents: number; lowStockCount: number };

export function createMonthlyReportHtml({ businessName, monthLabel, metrics, products, recommendations }: { businessName: string; monthLabel: string; metrics: ReportMetrics; products: ReportProduct[]; recommendations: string[] }) {
  const rows = products.map((product) => `<tr><td>${escapeHtml(product.productName)}</td><td>${product.unitsSold}</td><td>${product.currentStockUnits}</td><td>${formatBRL(product.revenueCents)}</td><td>${formatBRL(product.inventoryValueCents)}</td></tr>`).join("") || "<tr><td colspan=\"5\">Nenhum produto cadastrado.</td></tr>";
  const notes = recommendations.map((item) => `<li>${escapeHtml(item)}</li>`).join("") || "<li>Registre vendas e movimentações para receber recomendações.</li>";
  return `<!DOCTYPE html><html lang="pt-BR"><head><meta charset="utf-8"/><style>@page{margin:28px}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#080D2B;font-size:11px}h1{font-size:24px;margin:0 0 3px}h2{font-size:15px;margin:25px 0 10px;color:#168CCF}.subtitle{color:#577188;margin:0}.summary{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:20px}.metric{background:#F3F6F7;border:1px solid #CFE0EA;border-radius:10px;padding:12px}.metric span{display:block;color:#577188;font-size:10px;margin-bottom:5px}.metric strong{font-size:16px}table{width:100%;border-collapse:collapse}th{text-align:left;background:#080D2B;color:#fff;padding:9px;font-size:10px}td{padding:9px;border-bottom:1px solid #CFE0EA}li{margin:7px 0;line-height:1.4}.footer{margin-top:28px;color:#577188;font-size:9px}</style></head><body><h1>SK Água Gestão</h1><p class="subtitle">${escapeHtml(businessName)} · Relatório mensal · ${escapeHtml(monthLabel)}</p><h2>Resumo financeiro</h2><div class="summary"><div class="metric"><span>Resultado líquido</span><strong>${formatBRL(metrics.netResultCents)}</strong></div><div class="metric"><span>Faturamento</span><strong>${formatBRL(metrics.revenueCents)}</strong></div><div class="metric"><span>Quantidade de vendas</span><strong>${metrics.salesCount}</strong></div><div class="metric"><span>Unidades vendidas</span><strong>${metrics.soldStockUnits} galões</strong></div><div class="metric"><span>Ticket médio</span><strong>${metrics.ticketAverageCents === null ? "Ainda não calculado" : formatBRL(metrics.ticketAverageCents)}</strong></div><div class="metric"><span>Valor em estoque</span><strong>${formatBRL(metrics.inventoryValueCents)}</strong></div></div><h2>Produtos e estoque</h2><table><thead><tr><th>Produto</th><th>Vendidos</th><th>Estoque</th><th>Receita</th><th>Valor em estoque</th></tr></thead><tbody>${rows}</tbody></table><h2>Leitura do gestor</h2><ul>${notes}</ul><p class="footer">Documento gerado pelo SK Água Gestão.</p></body></html>`;
}
