import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { Card, ErrorState, IconAction, LoadingState, PageHeader } from "@/components/app-ui";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";
import { getLearningProgress, getNextTrack, learningTracks } from "@/shared/learning";

export default function LearningScreen() {
  const colors = useColors();
  const router = useRouter();
  const progressQuery = trpc.learning.progress.useQuery();
  const completed = progressQuery.data?.map((item) => item.lessonKey) ?? [];
  const progress = getLearningProgress(completed);
  const next = getNextTrack(completed);

  if (progressQuery.isLoading) return <ScreenContainer><LoadingState label="Carregando sua trilha..." /></ScreenContainer>;
  if (progressQuery.isError) return <ScreenContainer><ErrorState description="Não foi possível carregar seu progresso." onRetry={() => progressQuery.refetch()} /></ScreenContainer>;

  return <ScreenContainer className="px-4"><FlatList data={learningTracks} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><PageHeader eyebrow="Aprendizado aplicado" title="Aprender fazendo" action={<IconAction icon="info.circle.fill" label="Como funciona" onPress={() => router.push("/aprendizado/como-funciona" as never)} />} /><Text style={[styles.intro, { color: colors.muted }]}>Lições curtas para transformar os números da SK Água em decisões melhores.</Text><Card style={[styles.progressCard, { backgroundColor: colors.foreground, borderColor: colors.foreground }]}><View style={styles.progressTop}><View><Text style={styles.progressLabel}>SUA TRILHA</Text><Text style={styles.progressTitle}>{progress}% concluída</Text></View><View style={styles.progressCircle}><Text style={[styles.progressNumber, { color: colors.foreground }]}>{completed.length}</Text><Text style={[styles.progressOf, { color: colors.muted }]}>/ {learningTracks.length}</Text></View></View><View style={styles.progressTrack}><View style={[styles.progressFill, { width: `${progress}%`, backgroundColor: colors.primary }]} /></View><Text style={styles.progressHint}>{next ? `Próxima: ${next.title}` : "Você concluiu todas as lições."}</Text></Card><Text style={[styles.sectionTitle, { color: colors.foreground }]}>Trilha de gestão</Text></View>} renderItem={({ item, index }) => { const isDone = completed.includes(item.id); const isNext = !isDone && item.id === next.id; return <Pressable onPress={() => router.push(`/aprendizado/${item.id}` as never)} style={({ pressed }) => [styles.lesson, { backgroundColor: colors.surface, borderColor: isNext ? colors.primary : colors.border }, pressed && styles.pressed]}><View style={[styles.number, { backgroundColor: isDone ? colors.success : isNext ? colors.primary : colors.background, borderColor: isDone ? colors.success : isNext ? colors.primary : colors.border }]}>{isDone ? <IconSymbol name="checkmark" size={18} color="#FFFFFF" /> : <Text style={[styles.numberText, { color: isNext ? "#FFFFFF" : colors.muted }]}>{index + 1}</Text>}</View><View style={styles.lessonInfo}><View style={styles.lessonTitleRow}><Text style={[styles.lessonTitle, { color: colors.foreground }]} numberOfLines={1}>{item.title}</Text>{isNext ? <Text style={[styles.nextBadge, { color: colors.primary, backgroundColor: `${colors.primary}16` }]}>PRÓXIMA</Text> : null}</View><Text style={[styles.lessonObjective, { color: colors.muted }]} numberOfLines={2}>{item.objective}</Text><Text style={[styles.duration, { color: colors.muted }]}>{item.durationMinutes} min · {isDone ? "Concluída" : "Lição prática"}</Text></View><IconSymbol name="chevron.right" size={20} color={colors.muted} /></Pressable>; }} /></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingTop: 13, paddingBottom: 30, gap: 10 }, header: { gap: 10, marginBottom: 3 }, intro: { fontSize: 13, lineHeight: 19 }, progressCard: { gap: 14, padding: 17, marginTop: 3 }, progressTop: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, progressLabel: { color: "#BCE7FA", fontSize: 10, letterSpacing: 1, fontWeight: "800" }, progressTitle: { color: "#FFFFFF", fontSize: 21, lineHeight: 28, fontWeight: "800", marginTop: 4 }, progressCircle: { width: 52, height: 52, borderRadius: 26, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center", flexDirection: "row" }, progressNumber: { fontSize: 17, fontWeight: "800" }, progressOf: { fontSize: 10, fontWeight: "700" }, progressTrack: { height: 8, borderRadius: 8, backgroundColor: "#34405D", overflow: "hidden" }, progressFill: { height: "100%", borderRadius: 8 }, progressHint: { color: "#CFE0EA", fontSize: 12, fontWeight: "600" }, sectionTitle: { fontSize: 17, fontWeight: "800", marginTop: 5 }, lesson: { minHeight: 94, borderRadius: 19, borderWidth: 1, padding: 12, flexDirection: "row", alignItems: "center", gap: 10 }, number: { width: 40, height: 40, borderRadius: 14, borderWidth: 1, alignItems: "center", justifyContent: "center" }, numberText: { fontSize: 16, fontWeight: "800" }, lessonInfo: { flex: 1, gap: 4 }, lessonTitleRow: { flexDirection: "row", alignItems: "center", gap: 6 }, lessonTitle: { flexShrink: 1, fontSize: 14, fontWeight: "800" }, nextBadge: { overflow: "hidden", borderRadius: 5, paddingHorizontal: 5, paddingVertical: 3, fontSize: 8, fontWeight: "800" }, lessonObjective: { fontSize: 11, lineHeight: 16, fontWeight: "600" }, duration: { fontSize: 10, fontWeight: "700" }, pressed: { opacity: 0.7, transform: [{ scale: 0.99 }] } });
