import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { EmptyState, ErrorState, IconAction, LoadingState, PageHeader } from "@/components/app-ui";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useWorkspace } from "@/hooks/use-workspace";
import { formatBRL } from "@/shared/business";

export default function ProductsScreen() {
  const colors = useColors(); const router = useRouter(); const { data, isLoading, isError, refetch } = useWorkspace(); const products = data?.workspace?.products ?? [];
  if (isLoading) return <ScreenContainer><LoadingState /></ScreenContainer>;
  if (isError) return <ScreenContainer><ErrorState description="Não foi possível buscar seu estoque." onRetry={refetch} /></ScreenContainer>;
  return <ScreenContainer className="px-4"><FlatList data={products} keyExtractor={(item) => String(item.id)} contentContainerStyle={products.length ? styles.list : styles.emptyList} ListHeaderComponent={<View style={styles.header}><PageHeader eyebrow="Estoque" title="Seus produtos" action={<IconAction icon="plus.circle.fill" label="Cadastrar estoque" onPress={() => router.push("/produto/novo" as never)} />} /><Text style={[styles.caption, { color: colors.muted }]}>Cada modalidade de saída reduz o saldo do mesmo galão.</Text></View>} ListEmptyComponent={<EmptyState icon="shippingbox.fill" title="Seu estoque começa aqui" description="Cadastre os galões que você vende para registrar vendas e acompanhar reposições." actionLabel="Cadastrar estoque" onAction={() => router.push("/produto/novo" as never)} />} renderItem={({ item }) => { const isLow = item.stockUnits <= item.minimumStockUnits; return <Pressable onPress={() => router.push(`/produto/${item.id}` as never)} style={({ pressed }) => [styles.productCard, { backgroundColor: colors.surface, borderColor: isLow ? colors.warning : colors.border }, pressed && styles.pressed]}><View style={[styles.drop, { backgroundColor: `${colors.primary}18` }]}><IconSymbol name="drop.fill" size={23} color={colors.primary} /></View><View style={styles.productInfo}><View style={styles.productTitleLine}><Text style={[styles.productName, { color: colors.foreground }]} numberOfLines={1}>{item.name}</Text>{!item.active ? <Text style={[styles.inactive, { color: colors.muted, backgroundColor: colors.border }]}>INATIVO</Text> : null}</View><Text style={[styles.meta, { color: colors.muted }]}>{item.stockUnits} galões · mínimo {item.minimumStockUnits}</Text><Text style={[styles.meta, { color: colors.muted }]}>{formatBRL(item.defaultPriceCents)} · custo {formatBRL(item.unitCostCents)}</Text></View><View style={styles.trailing}>{isLow ? <IconSymbol name="exclamationmark.triangle.fill" size={18} color={colors.warning} /> : null}<IconSymbol name="chevron.right" size={21} color={colors.muted} /></View></Pressable>; }} /></ScreenContainer>;
}
const styles = StyleSheet.create({ list: { paddingTop: 13, paddingBottom: 30, gap: 10 }, emptyList: { flexGrow: 1, paddingTop: 13, paddingBottom: 30 }, header: { gap: 8, marginBottom: 13 }, caption: { fontSize: 13, lineHeight: 19 }, productCard: { minHeight: 104, borderWidth: 1, borderRadius: 20, padding: 14, flexDirection: "row", alignItems: "center", gap: 12 }, drop: { width: 48, height: 48, borderRadius: 16, alignItems: "center", justifyContent: "center" }, productInfo: { flex: 1, gap: 4 }, productTitleLine: { flexDirection: "row", alignItems: "center", gap: 7 }, productName: { flexShrink: 1, fontSize: 16, fontWeight: "800" }, meta: { fontSize: 12, lineHeight: 17, fontWeight: "600" }, inactive: { borderRadius: 6, overflow: "hidden", fontSize: 9, paddingHorizontal: 6, paddingVertical: 3, fontWeight: "800" }, trailing: { alignItems: "flex-end", justifyContent: "space-between", alignSelf: "stretch", paddingVertical: 2 }, pressed: { opacity: 0.72, transform: [{ scale: 0.99 }] } });
