import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { EmptyState, LoadingState, PageHeader } from "@/components/app-ui";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useWorkspace } from "@/hooks/use-workspace";
import { useSaleCart } from "@/lib/sale-cart";
import { formatBRL, getMaximumQuantity } from "@/shared/business";

export default function SellScreen() {
  const colors = useColors(); const router = useRouter(); const { data, isLoading } = useWorkspace(); const { lines, setQuantity } = useSaleCart();
  const products = (data?.workspace?.products ?? []).filter((product) => product.active && product.stockUnits > 0 && product.exitModes.some((mode) => mode.active));
  const cartTotal = lines.reduce((total, line) => { const product = products.find((item) => item.id === line.productId); const mode = product?.exitModes.find((item) => item.id === line.exitModeId); return total + (mode ? mode.priceCents * line.quantity : 0); }, 0);
  const totalUnits = lines.reduce((total, line) => { const product = products.find((item) => item.id === line.productId); const mode = product?.exitModes.find((item) => item.id === line.exitModeId); return total + (mode ? mode.stockUnits * line.quantity : 0); }, 0);
  if (isLoading) return <ScreenContainer><LoadingState /></ScreenContainer>;
  return <ScreenContainer className="px-4"><FlatList data={products} keyExtractor={(item) => String(item.id)} contentContainerStyle={products.length ? styles.list : styles.emptyList} ListHeaderComponent={<View style={styles.header}><PageHeader eyebrow="Venda rápida" title="O que saiu hoje?" action={lines.length ? <View style={[styles.cartCounter, { backgroundColor: colors.foreground }]}><Text style={styles.cartCounterText}>{lines.reduce((sum, item) => sum + item.quantity, 0)}</Text></View> : <View style={[styles.cartCounter, { backgroundColor: colors.surface, borderColor: colors.border }]}><IconSymbol name="cart.fill" size={21} color={colors.muted} /></View>} /><Text style={[styles.subtitle, { color: colors.muted }]}>A quantidade máxima acompanha o saldo único de cada galão.</Text></View>} ListEmptyComponent={<EmptyState icon="shippingbox.fill" title="Não há galões disponíveis" description="Cadastre um produto e informe o saldo em estoque antes de registrar uma venda." actionLabel="Cadastrar estoque" onAction={() => router.push("/produto/novo" as never)} />} renderItem={({ item: product }) => <View style={[styles.productCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.productHeader}><View style={[styles.productIcon, { backgroundColor: `${colors.primary}16` }]}><IconSymbol name="drop.fill" size={22} color={colors.primary} /></View><View style={styles.productInfo}><Text style={[styles.productName, { color: colors.foreground }]}>{product.name}</Text><Text style={[styles.stockText, { color: colors.muted }]}>{product.stockUnits} galões disponíveis</Text></View></View><FlatList horizontal showsHorizontalScrollIndicator={false} data={product.exitModes.filter((mode) => mode.active)} keyExtractor={(mode) => String(mode.id)} contentContainerStyle={styles.modes} ItemSeparatorComponent={() => <View style={{ width: 9 }} />} renderItem={({ item: mode }) => {
    const selected = lines.find((line) => line.exitModeId === mode.id); const quantity = selected?.quantity ?? 0;
    const inCartForProduct = lines.filter((line) => line.productId === product.id && line.exitModeId !== mode.id).reduce((sum, line) => { const other = product.exitModes.find((item) => item.id === line.exitModeId); return sum + (other?.stockUnits ?? 0) * line.quantity; }, 0);
    const max = quantity + getMaximumQuantity(product.stockUnits - inCartForProduct - quantity * mode.stockUnits, mode.stockUnits);
    const change = (next: number) => setQuantity({ exitModeId: mode.id, productId: product.id, quantity: Math.max(0, Math.min(next, max)) });
    return <View style={[styles.modeCard, { borderColor: quantity ? colors.primary : colors.border, backgroundColor: quantity ? `${colors.primary}0D` : colors.background }]}><Text style={[styles.modeName, { color: colors.foreground }]} numberOfLines={2}>{mode.name}</Text><Text style={[styles.modePrice, { color: colors.primary }]}>{formatBRL(mode.priceCents)}</Text><Text style={[styles.modeConsumption, { color: colors.muted }]}>{mode.stockUnits} galão{mode.stockUnits > 1 ? "ões" : ""}</Text><View style={styles.stepper}><Pressable onPress={() => change(quantity - 1)} disabled={!quantity} style={({ pressed }) => [styles.step, { backgroundColor: colors.surface, borderColor: colors.border }, (!quantity || pressed) && styles.pressed]}><Text style={[styles.stepText, { color: colors.foreground }]}>−</Text></Pressable><Text style={[styles.quantity, { color: colors.foreground }]}>{quantity}</Text><Pressable onPress={() => change(quantity + 1)} disabled={quantity >= max} style={({ pressed }) => [styles.step, { backgroundColor: colors.primary }, (quantity >= max || pressed) && styles.pressed]}><Text style={styles.plusText}>+</Text></Pressable></View></View>;
  }} /></View>} ListFooterComponent={lines.length ? <View style={styles.bottom}><View><Text style={[styles.totalHint, { color: colors.muted }]}>{totalUnits} galão{totalUnits !== 1 ? "ões" : ""} selecionado{totalUnits !== 1 ? "s" : ""}</Text><Text style={[styles.total, { color: colors.foreground }]}>{formatBRL(cartTotal)}</Text></View><Pressable onPress={() => router.push("/venda/revisao" as never)} style={({ pressed }) => [styles.review, { backgroundColor: colors.primary }, pressed && styles.pressed]}><Text style={styles.reviewText}>Revisar</Text><IconSymbol name="chevron.right" size={19} color="#FFFFFF" /></Pressable></View> : null} /></ScreenContainer>;
}
const styles = StyleSheet.create({ list: { paddingTop: 13, paddingBottom: 28, gap: 11 }, emptyList: { flexGrow: 1, paddingTop: 13, paddingBottom: 28 }, header: { gap: 8, marginBottom: 7 }, subtitle: { fontSize: 13, lineHeight: 19 }, cartCounter: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" }, cartCounterText: { color: "#FFFFFF", fontSize: 16, fontWeight: "800" }, productCard: { borderRadius: 22, borderWidth: 1, paddingVertical: 15, gap: 14 }, productHeader: { paddingHorizontal: 15, flexDirection: "row", alignItems: "center", gap: 11 }, productIcon: { width: 44, height: 44, borderRadius: 14, alignItems: "center", justifyContent: "center" }, productInfo: { flex: 1, gap: 3 }, productName: { fontSize: 16, fontWeight: "800" }, stockText: { fontSize: 12, fontWeight: "600" }, modes: { paddingHorizontal: 15 }, modeCard: { width: 169, minHeight: 195, borderRadius: 17, borderWidth: 1, padding: 12, justifyContent: "space-between", gap: 5 }, modeName: { fontSize: 13, lineHeight: 18, fontWeight: "800", minHeight: 36 }, modePrice: { fontSize: 18, fontWeight: "800", letterSpacing: -0.2 }, modeConsumption: { fontSize: 11, fontWeight: "600" }, stepper: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 5 }, step: { width: 35, height: 35, borderRadius: 11, alignItems: "center", justifyContent: "center", borderWidth: 1 }, stepText: { fontSize: 22, lineHeight: 25, fontWeight: "500" }, plusText: { color: "#FFFFFF", fontSize: 22, lineHeight: 25, fontWeight: "500" }, quantity: { fontSize: 17, fontWeight: "800" }, bottom: { marginTop: 9, borderRadius: 20, padding: 15, flexDirection: "row", alignItems: "center", justifyContent: "space-between", backgroundColor: "#FFFFFF", borderColor: "#CFE0EA", borderWidth: 1 }, totalHint: { fontSize: 11, fontWeight: "700" }, total: { fontSize: 21, lineHeight: 27, fontWeight: "800", letterSpacing: -0.3 }, review: { minHeight: 45, paddingHorizontal: 15, borderRadius: 13, flexDirection: "row", alignItems: "center", gap: 3 }, reviewText: { color: "#FFFFFF", fontSize: 14, fontWeight: "800" }, pressed: { opacity: 0.65, transform: [{ scale: 0.98 }] } });
